version: '3'
services:
    mongodb:
      image: mongo
      ports:
        - "27017:27017"

    mongo-seed:
      image: bilges/clinicalreportingdbrestapi_mongo-seed
      links:
        - mongodb

    api:
      image: bilges/clinicalreportingdbrestapi_api
      ports:
        - "5000:5000"
      # volumes:
      #   - ./app:/app:rw
      depends_on:
        - mongodb

    filedeploy:
      image: bilges/filedeploy
      volumes:
        - dependencyF:/mnt

    ClinicalReportR: 
      image: bilges/clinicalreportr
      volumes:
        - dependencyF:/data
        - ./ReportApp:/inout
      network_mode: "host"
      depends_on:
        - api
        - mongodb
        - mongo-seed
        - filedeploy
      # stdin_open: true
      # tty: true
volumes:
  dependencyF:
